version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: myrabbit
    networks:
      - yowsupnet
  yowsup-microservice:
    image: oliveirasevandro/yowsup-microservice:latest
    environment:
      - USERNAME=<your_account_number>
      - PASSWORD=<your_password>
      - TOKEN_RESEND_MESSAGES=<your_token_resend_messages>
      - ENDPOINT_RESEND_MESSAGES=<your_endpoint_resend_messages>
      - AMQP_URI=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "80:80"
    networks:
      - yowsupnet
networks:
  yowsupnet:
